### ISSUE TITLE
Move `/discover-cluster` endpoint to Flask-RESTful

### ISSUE THREAD

**Issue by ikalnytskyi** [Mirantis/Kostyor#55]
We need to move this endpoint to Flask-RESTful, as well, as make some cosmetic changes to it. 

Taking into account that we might support various implementation, perhaps it makes sense to do something like:

```
/clusters/discover/openstack
```

Opinion on the design is needed.

**Comment by sc68cal** [comment]
I think the problem is that `/clusters/discover/openstack` sort of clashes with our `/clusters/<cluster_id>` scheme - I'd prefer that we avoid that.

**Comment by ikalnitsky** [comment]
Any idea on this? Having `/discover-cluster` endpoint is a bit verbose, in my opinion. Maybe just `/clusters/discover` with JSON payload about the method and params?

**Comment by jvarlamova** [comment]
Maybe something like '/discovery/openstack'?

**Comment by ikalnitsky** [comment]
@jvarlamova I was thinking about this, the thing is I don't like here is it's not clear what we are going to discover. :( Thought, it's a good suggestion and should be considered.

**Comment by sc68cal** [comment]
:neutral_face: I think maybe  POST to `/clusters/discover/` with a JSON payload might be the best fit?

**Comment by ikalnitsky** [comment]
I guess yes.

```http
POST /clusters/discover HTTP/1.1
Content-Type: application/json

{
    "method": "openstack",
    "parameters": {  }
}
```

where `parameters` is an optional schemaless argument that will be passed directly to discovery driver. In case of openstack method, it could be:

```json
{
    "username": "stack",
    "password": "stack",
    "project_name": "stack",
    "auth_url": "http://192.168.0.2:5000/v2.0"
}
```

**Comment by sc68cal** [comment]
yep - that looks like a good way forward to me.

**Comment by sc68cal** [comment]
Let's defer this.

https://github.com/sc68cal/Kostyor/issues/73#issuecomment-254848251
