### ISSUE TITLE
Get rid of intermediate `cluster` node in `/clusters` response

### ISSUE THREAD

**Issue by ikalnytskyi** [Mirantis/kostyor#73]
So far Kostyor's endpoint that lists clusters has the following interface:

``` http
GET /clusters HTTP/1.1

{
    "clusters": [
        { "..." },
        { "..." }
    ]
}
```

There's no need in intermediate `clusters` node. Besides, in order to be consistent with `/upgrades`, `/hosts` and `/services` endpoints, let's just respond with a simple list:

``` http
GET /clusters HTTP/1.1

[
    { "..." },
    { "..." }
]
```

The fix must be implemented first on Kostyor-cli side, so it can work with both formats for a while.

**Comment by jvarlamova** [comment]
Agree with it.

**Comment by jvarlamova** [comment]
I'll take this issue if nobody minds, OK?

**Comment by ikalnitsky** [comment]
Sure. :) Thank you.

**Comment by sc68cal** [comment]
I think this is low priority. We need to focus on the upgrade engine and driver. Let's defer this please, as I said on the call this morning.
