### ISSUE TITLE
Fuel-ccp upgrade driver

### ISSUE THREAD

**Issue by sc68cal** [Mirantis/kostyor#89]

**Comment by sc68cal** [comment]
We have a demo that we can follow for how they handle upgrades:

https://asciinema.org/a/3xntr03c4sse2e11i6ae76541

Basically, a fuel-ccp upgrade driver will behave very similar to the ansible driver. There will most likely be a privileged deployment host that we will need to access - pass in some generated yaml, and invoke `fuel-ccp deploy`

**Comment by ikalnytskyi** [comment]
Naive implementation is available at https://github.com/Mirantis/kostyor-fuelccp
